# Generated by Django 5.2.17 on 2026-08-06 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], db_index=True, default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('current_company', models.CharField(blank=True, max_length=500, null=True)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('total_companies', models.PositiveIntegerField(default=0)),
                ('scraped_companies', models.PositiveIntegerField(default=0)),
                ('failed_companies', models.PositiveIntegerField(default=0)),
                ('start_page', models.PositiveIntegerField(default=1)),
                ('end_page', models.PositiveIntegerField(default=0)),
                ('workers', models.PositiveSmallIntegerField(default=2)),
                ('delay_min', models.FloatField(default=1.0)),
                ('delay_max', models.FloatField(default=3.0)),
                ('retry_count', models.PositiveSmallIntegerField(default=3)),
                ('timeout', models.PositiveIntegerField(default=30)),
                ('headless', models.BooleanField(default=True)),
                ('output_excel', models.BooleanField(default=True)),
                ('output_csv', models.BooleanField(default=True)),
                ('output_database', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
