# Generated by Django 5.2.17 on 2026-08-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_job_created_records_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], db_index=True, default='pending', max_length=20),
        ),
    ]
