# Generated by Django 5.2.17 on 2026-08-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pause_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='stop_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
