# Generated by Django 5.2.17 on 2026-08-06 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], db_index=True, max_length=20)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('total_records', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='scraper.job')),
            ],
            options={
                'db_table': 'exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
