# Generated by Django 5.2.17 on 2026-08-06 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=500)),
                ('founders', models.TextField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('current_stage', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('team_size', models.CharField(blank=True, max_length=100, null=True)),
                ('member_since', models.CharField(blank=True, max_length=100, null=True)),
                ('key_highlights', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=1000, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('engagement_level', models.CharField(blank=True, max_length=255, null=True)),
                ('smart_card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('startup_type', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_url', models.URLField(max_length=500, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='scraper.job')),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
