# Generated by Django 5.2.17 on 2026-08-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_sector_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
